export interface employee{
  birthDate?:string,
  description?:string,
  email?:string,
  firstName?:string,
  function?:string,
  gender?:string,
  hireDate?:string,
  lastName?:string,
  linkedin?:string,
  phoneNumber?:string,
  profilePicture?:string,
  resignationDate?:string,
  startDate?:string,
  unit?:{
    name:string
  },
  username?:string
}
