language: node_js
node_js:
- 4.2.1
sudo: false
install:
- npm install -g npm
- npm install -g grunt-cli
- npm install -g bower
- npm install
- bower install
- grunt build
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: andreas.evers@ordina.be
  password:
    secure: "AzyzQCV8jrsX/wOqAH175Ro2kaPM7G5lruUAEiN89EyRGYO+r6F2fhODayOALV4m5fcCIiBd5TVJYhTIFWoavmKhxbmLzuAICJAnKSupTIHePVdKCDO7lubCiU0peesivVcPiB67fzWOKVXuPChdy9fR7dZCUqGfhadrccVTq/Hofiq/aTaLGzIE6GKqtQ4o0mEJRsDZ6+2EhPBjjgiRpzd/JzthcqUP6mfZrAxAJilVuEOQT20qwHcInRVhaOpI2RQZVKbn8KKSBoXbJL+7K5veUsxX4jfZH7rt9nv04gHpAX2Od7YoFLXR8n/NZJT8Q5Us6me8rHzVOvDHMdaF1ov9gCWi5vFj6y5YpV3sK0sDB98ykfSuD/na9hEd2svqEPUiPErBpmiECZg82Z+FuPvl8VhEEGdvmETUmaFKFweH5WDJ/Jd9lnMN2xJuU6pYHQK8Fi8iJ93qLnOO8f5bea53hOKPJx4aj8OWiJVAvlNPckShQDJDYcAZYQnLCGCrg2iIrp0luS+AskW8ipN7DojwvZKexTNXbaBRdsWGtcp85tDNP0xKoZXfPVVf5NjJieq1jNLGTpo48IqHuZTFPqmFKxOYv0ZXXO7SVajToOzFeCzXzpwlz13e+v5aq12wb4gWjAVcraZkFuPrvNkOJHVijROsXYpMZOZbP2GisqA="
  organization: OrdinaBelgiumNV
  space: development
  on:
    repo: oraj-360/front-end
    branch: master
