language: node_js
node_js:
- 4.2.1
sudo: false
install:
- npm install
- npm install -g grunt-cli
- bower install
- grunt build
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: andreas.evers@ordina.be
  password:
    secure: "FKZv5rboSaP6Pyjrn3T4et+DK2BL1iv2L4XAMt4CfgZ2rB+nEv8M6ocXqFNXBYgpx1PRhCfNwK33ErukOQSH7oFb15XO2y0vTX7UV0zgmLRulPqabUmLyEk4Xg9jhhhLJ/96aGpUQF4GGHNuJ9jwVqRsYenOtjJK2959My9WdIJ0p2P00Byaq/3GmxrEFLJCfZ13ewQrdtSpL6YYUTAZbkhOpz4yruwubyWu3HP9pVwVq/H/lNsrMPHPRMSSjMlIKpEjKDGCEN0o7oCPUE3SdyrpxfRJgejZ4yk8ffptgdkPTm7HKvWUetzZVHTcI9LVOwVdB3xaON0AouaFtFitmJsSkylrteIHosm+U/lmPE21fg0cgFxEFpO6d6hjEFbaaFY9UXUXEoIvleKkevjTR9ronRCiNKnoHxhe3DeXNL9DixCd3m8WZbSzicRGXP+n9uPZREb9XUIhoaGjP0TMJ8Lj9OxzFXrtSMCfZppFEIQ4sWTqEkc0UVuJUiAIh/sKZicCYooKls0WY3dRy0lQBNjgV4m0a0f4QAawqfH0nmPSwRq6BBVFHFIhAFTa9SpYcykV7UGBZYWYb39jk/SiweZ7A5Vc0aG87A5C6pdyhscC3zcZFixILYFfI59oPRSYeI3DxxLZ4ab56sKtdzmg3SXIJTCf7qAtvMijjZBwTRc="
  organization: OrdinaBelgiumNV
  space: development
  on:
    repo: oraj-360/front-end
    branch: master
