language: node_js
node_js:
- '0.12'
sudo: false
install:
- npm install
- npm install -g bower
- bower install
- grunt build
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: andreas.evers@ordina.be
  password:
    secure: "S15Q/022reM0Ijc8os1h2LGiEljk9hM8/5XmOOyWmaMwSlJsuTJ0YJPqvr9+O6RAzTT5w17dn3Eu8OUNnsx58E2N+zKS6bmeuu3xVuYvDI8hq1bRFG2fIq0yFjKNmm45K8EEB3KeVNdxOgtlSgdGuFaFTSSpHIWw4n8SBWTMmMtNYi7oaGx9FHGUv4u5U2hcvi35McgHeZjm8sfLcD3bZ4I4a70ELy3GP4eMTiOgWj9v2Ki2DATRYdf3JP6Fiam0EWsYaj7QNoIcDAQRfbpmt7QbPW3qCNGN+173RXcPKln2ZC11Nt+Wwy0Jin3uWd9UeBAAWBKU7/x/mpUhjb4Cgv+OPLhxCcb5iMKo5sejQBmL41cGSJ/OxRJcMr9WP3e1ja121YpTEgBAsTGz7eT1k02aGz4obkz2mEPfU8CUmD3aYgH2vAXtxHNqLd3QsamAxomuVVa2cXhKXbzV7jGxB5M/iqgF8MAtn+x9RTrMzHcQQpoTEc2f0mSsw7feii9UmzJ0jy62yi6teKGmO74H8Jk7OjAqorTsbXffQrfKghzNeNN8nKDjlSASMKA7OwbbYkd+cbfgxfpv3NQIvNTqAwIbhmSkfdt+FKPnNxRm+XAmcHcQYO77Igx+4PFtGaQW1CCEpRmrE5UEmvylocOMp5EjRc8bGyMC9AJQqAQNgk4="
  organization: OrdinaBelgiumNV
  space: development
  on:
    repo: oraj-360/front-end
    branch: master
