language: node_js
node_js:
- 4.2.1
sudo: false
install:
- npm install -g npm
- npm install -g grunt-cli
- npm install
- bower install
- grunt build
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: andreas.evers@ordina.be
  password:
    secure: "PHuW7l1rDqFWIPi00qcJu6imXIBgWnAJCwXNP8Xbv25uOe4zSxMvWef55CYlc3720J3IyZ0DaKYBGhIWyFModyjh3TJJ2amWe3btidnbOYQrY+HwvP7KJcZynHcvpO1UHwxupqmFjjna1zgww3lQxEw5FerP9sBLB5COjz6RThFMkS/wNobbeOKR/sJ8c0TH70XVrZlOqoLgwwSSQNPY9KbxVAhenDKylC7ZIqtq75RHlxOJNwk5IsOSTPa0AYqykbihETI0st8KoMh4AStP25XB+KrnvVnFGUVLwYHvCfDM8TS8F771M4g85CWMmQh4+kp5o5tlUy4Nab11lhq8Go4JExh5rrDEXz8XCVe2F3oBuuLvAqQAWc6bAuKrJ2v61L/LwOXn6xJtiy7g3d9Kn8Yd8+5NHSZ93Pb9FV7cO21HbaCHLEDd3f+gtTIXlFkcdhHWdGySoG7x1mg5McdLiyJvJWGR4i+jOdvTspqVt2IfBAincy6Wjh4U/1tGPG8g7HTHII7lJRVPa5tmnnZnF4EjZqig6hngQ2L+qPoSlK9PQ0P00htAiRvlpdQlyYVVX9B7uU1NeBiz7K2K+Fq5qPGQpqAZ/sjWxqeHQ92jnD/ZiFAYrAMoWTCGOS2KLzAk8xo9bwOgHNZXIZopeCfK9aoB4dZTiUGRYxWzmWfBaXY="
  organization: OrdinaBelgiumNV
  space: development
  on:
    repo: oraj-360/front-end
    branch: master
