language: node_js
node_js:
- '0.12'
sudo: false
install:
- npm install
- npm install -g bower
- bower install
- npm install -g grunt-cli
- grunt build
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: andreas.evers@ordina.be
  password:
    secure: "KLA/wHIB42z+cz8MEVAn1uIq6nROo1bebtXi66jd4L/YQ7ffbGtO9/B7e0zXmoW4KLnEHxgHRo9yiT7uZOtr4M4qGCWo4XhOJSgBz6gp358DHIAVWMje22z7Mee4Ogz79mtw2DYWSySA9xWm/mIaoGKwV3atA0y1SwEonHSH11grDrduxQaLQHI8wr+wT1HDORM6XoGtzVLy7F9H/B3xVG4x9jBp5qd5PJJrhR7U2CZ3boGfUERXrKGRWOKLigQSXHPmBjGhYRLBpwZvW2faN9cWCmFIqJZBvD6GMEbRnoBar2StY90LiT8++LzeUBgLgqfxZJR39UKrJP8QoMRkB5f71XPlBWK4qW0tnq9so2CEFHWBpL4eAq1iAaJqeXEr4IWlKtRhm8dRjcfk7XWbKCxsMoJ3pCXU7YYyanc+Azhz6AgxH6Q8U/O72BKvalQY+fIQyMCC5ZV12Gm+n+ma2OvuRu64vto58pXQcGDOZWigl3tQBym/LAJa8OLfmZWTQS7P+YmSoo+0xQXmw6Bdrg1+JRSRuha10Ua2sPCNc51zlNHoEmxJyf9XQByQuX3tzKLB3qXzniSM0zWiFqTUSq8TKsnUPDhSn8WZET95S6FM8KbOGsmOtpxwCmu+B8c5yrspoSsrN8zMp0nLVoaMfjoZ7NAMF82CcnXwiIrL46k="
  organization: OrdinaBelgiumNV
  space: development
  on:
    repo: oraj-360/front-end
    branch: master
